import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, setDefaultTimeout, test } from 'bun:test';
import { extractExternalClassSource } from '../../../../src/extractor/extract-external-class-source.js';
import { resolveWithResolutionCache } from '../../../../src/resolve-with-cache.js';

// Gradle invocations take 10–30 s each; this scenario chains several in beforeAll.
setDefaultTimeout(120_000);

/**
 * Real-Gradle scenario: Gradle resolves exactly one version when multiple versions of the same
 * library exist in the dependency graph (direct vs. transitive conflict).
 *
 * Dependency graph:
 *   app ──direct──▶ widget-lib:2.0.0
 *   app ──────────▶ adapter:1.0.0 ──api──▶ widget-lib:1.0.0   (transitive)
 *
 * Gradle's "highest version wins" strategy resolves widget-lib to 2.0.0.
 * The tool must report the 2.0.0 artifact, not 1.0.0.
 *
 * beforeAll/afterAll are registered only when scenarioReady is true to avoid bun
 * counting them as unnamed skipped test slots when the describe block is skipped.
 *
 * Requires wrapper JARs generated by scripts/ensure-scenario-wrappers.sh.
 * Silently skipped in CI when wrappers are absent.
 */

const scenarioRoot = path.resolve(import.meta.dir);
const libRoot = path.join(scenarioRoot, 'lib');
const adapterRoot = path.join(scenarioRoot, 'adapter');
const appRoot = path.join(scenarioRoot, 'app');

const libWrapperJar = path.join(libRoot, 'gradle/wrapper/gradle-wrapper.jar');
const adapterWrapperJar = path.join(adapterRoot, 'gradle/wrapper/gradle-wrapper.jar');
const appWrapperJar = path.join(appRoot, 'gradle/wrapper/gradle-wrapper.jar');
const widgetSrc = path.join(libRoot, 'src/main/java/com/example/widget/Widget.java');

const scenarioReady =
  fs.existsSync(libWrapperJar) && fs.existsSync(adapterWrapperJar) && fs.existsSync(appWrapperJar);

async function runGradle(projectDir: string, ...args: string[]): Promise<void> {
  const gradlew = path.join(projectDir, 'gradlew');
  const proc = Bun.spawn([gradlew, '--no-daemon', '--quiet', ...args], {
    cwd: projectDir,
    env: { ...process.env },
    stdout: 'inherit',
    stderr: 'inherit',
  });
  const code = await proc.exited;
  if (code !== 0) {
    throw new Error(`Gradle ${args.join(' ')} in ${path.basename(projectDir)} exited with code ${code}`);
  }
}

// Shared state — populated by beforeAll, torn down by afterAll.
let sharedLocalRepo = '';
let sharedTmpDir = '';
let originalWidgetSrc = '';

// Register lifecycle hooks only when the scenario is runnable.
// This prevents bun from counting them as unnamed skipped test slots.
if (scenarioReady) {
  beforeAll(async () => {
    sharedTmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'jvmsrc-ver-conflict-'));
    sharedLocalRepo = path.join(sharedTmpDir, 'local-repo');
    fs.mkdirSync(sharedLocalRepo, { recursive: true });

    originalWidgetSrc = fs.readFileSync(widgetSrc, 'utf8');
    process.env.JVMSRC_LOCAL_MAVEN_REPO = sharedLocalRepo;

    // Publish widget-lib:1.0.0 — only render().
    await runGradle(libRoot, 'publish', '-Pversion=1.0.0');

    // Add animate() and publish widget-lib:2.0.0, then restore source.
    const v2Src = originalWidgetSrc.replace(
      /(\s*}\s*)$/,
      `
    /** Animates the widget. Added in v2.0.0. */
    public String animate() {
        return "animated";
    }
$1`,
    );
    fs.writeFileSync(widgetSrc, v2Src, 'utf8');
    await runGradle(libRoot, 'publish', '-Pversion=2.0.0');
    fs.writeFileSync(widgetSrc, originalWidgetSrc, 'utf8');

    // Publish adapter:1.0.0 — transitively depends on widget-lib:1.0.0.
    await runGradle(adapterRoot, 'publish');
  });

  afterAll(() => {
    if (originalWidgetSrc) {
      fs.writeFileSync(widgetSrc, originalWidgetSrc, 'utf8');
    }
    delete process.env.JVMSRC_LOCAL_MAVEN_REPO;
    try {
      fs.rmSync(sharedTmpDir, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  });
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe.skipIf(!scenarioReady)('gradle/version-conflict scenario (real Gradle)', () => {
  let prevCache: string | undefined;
  let tmpCache: string;

  beforeEach(() => {
    tmpCache = fs.mkdtempSync(path.join(os.tmpdir(), 'jvmsrc-vc-cache-'));
    prevCache = process.env.JVMSRC_CACHE_ROOT;
    process.env.JVMSRC_CACHE_ROOT = tmpCache;
  });

  afterEach(() => {
    if (prevCache === undefined) {
      delete process.env.JVMSRC_CACHE_ROOT;
    } else {
      process.env.JVMSRC_CACHE_ROOT = prevCache;
    }
    try {
      fs.rmSync(tmpCache, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  });

  test('resolved artifact version is 2.0.0 (direct dep wins over transitive 1.0.0)', async () => {
    const resolved = await resolveWithResolutionCache(appRoot, { forceRefresh: true });
    expect(resolved.ok).toBe(true);
    if (!resolved.ok) return;

    const allArtifacts = resolved.output.modules
      .flatMap((m) => m.configurations)
      .flatMap((c) => c.artifacts);

    const widgetArtifacts = allArtifacts.filter((a) => a.name === 'widget-lib');

    // Gradle deduplicates: only one version of widget-lib should appear.
    const versions = [...new Set(widgetArtifacts.map((a) => a.version).filter(Boolean))];
    expect(versions).toHaveLength(1);
    expect(versions[0]).toBe('2.0.0');

    // The resolved jarPath must reference the 2.0.0 artifact.
    const jar = widgetArtifacts[0]?.jarPath ?? '';
    expect(jar).toContain('2.0.0');
    expect(jar).not.toContain('1.0.0');
  });

  test('extracted Widget source is from 2.0.0 — contains animate() absent in 1.0.0', async () => {
    const resolved = await resolveWithResolutionCache(appRoot, { forceRefresh: true });
    expect(resolved.ok).toBe(true);
    if (!resolved.ok) return;

    const got = await extractExternalClassSource(resolved.output, {
      className: 'com.example.widget.Widget',
    });
    expect(got.ok).toBe(true);
    if (!got.ok) return;

    // animate() exists only in 2.0.0; confirms we read from the correct JAR.
    expect(got.source).toContain('animate');
    expect(got.source).toContain('render');
  });

  test('Gradle cache does not bleed: tool returns correct version even when 1.0.0 jar is in ~/.gradle', async () => {
    // Both 1.0.0 and 2.0.0 are now cached by Gradle after beforeAll published them.
    // Resolve app — must still report 2.0.0, not 1.0.0.
    const resolved = await resolveWithResolutionCache(appRoot, { forceRefresh: true });
    expect(resolved.ok).toBe(true);
    if (!resolved.ok) return;

    const widgetArt = resolved.output.modules
      .flatMap((m) => m.configurations)
      .flatMap((c) => c.artifacts)
      .find((a) => a.name === 'widget-lib');

    expect(widgetArt?.version).toBe('2.0.0');
  });
});
