import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, setDefaultTimeout, test } from 'bun:test';
import { extractExternalClassSource } from '../../../../src/extractor/extract-external-class-source.js';
import { resolveSourcesJar } from '../../../../src/resolvers/gradle/resolve-sources-jar.js';
import type { ResolutionOutput } from '../../../../src/resolvers/resolution-output.js';
import { resolveWithResolutionCache } from '../../../../src/resolve-with-cache.js';

setDefaultTimeout(120_000);

/**
 * Real-Gradle scenario: snapshot publication via local Maven repository.
 *
 * The test:
 *   1. Publishes `com.example:lib:1.0.0-SNAPSHOT` from `producer/` to a temp local Maven repo.
 *   2. Resolves `consumer/` (which depends on that snapshot) and verifies the `greet` method is visible.
 *   3. Adds a new `farewell()` method to `Greeter.java` and republishes.
 *   4. Verifies that `resolveWithResolutionCache` automatically detects the new JAR content
 *      (via local-artifact digest) and re-invokes Gradle — `farewell` appears WITHOUT forceRefresh.
 *   5. Also verifies the inverse: if forceRefresh is false and content truly hasn't changed,
 *      the cache is hit (same `resolvedAt` timestamp).
 *
 * Requires:
 *   - `gradle/wrapper/gradle-wrapper.jar` present in both `producer/` and `consumer/`
 *     (generated by scripts/ensure-scenario-wrappers.sh)
 *
 * These tests are intentionally skipped when either wrapper JAR is absent (CI without Gradle).
 */

const scenarioRoot = path.resolve(import.meta.dir);
const producerRoot = path.join(scenarioRoot, 'producer');
const consumerRoot = path.join(scenarioRoot, 'consumer');
const producerWrapperJar = path.join(producerRoot, 'gradle/wrapper/gradle-wrapper.jar');
const consumerWrapperJar = path.join(consumerRoot, 'gradle/wrapper/gradle-wrapper.jar');
const greeterSrc = path.join(producerRoot, 'src/main/java/com/example/lib/Greeter.java');

const scenarioReady = fs.existsSync(producerWrapperJar) && fs.existsSync(consumerWrapperJar);

/** Spawn a Gradle task in a project dir. JVMSRC_LOCAL_MAVEN_REPO must already be set on process.env. */
async function runGradle(projectDir: string, task: string): Promise<void> {
  const gradlew = path.join(projectDir, 'gradlew');
  const proc = Bun.spawn([gradlew, task, '--no-daemon', '--quiet'], {
    cwd: projectDir,
    env: { ...process.env },
    stdout: 'inherit',
    stderr: 'inherit',
  });
  const code = await proc.exited;
  if (code !== 0) {
    throw new Error(`Gradle task '${task}' in ${projectDir} exited with code ${code}`);
  }
}

/** Wrapper that calls extractExternalClassSource with on-demand sources JAR resolution. */
async function extractWithSources(output: ResolutionOutput, className: string) {
  return extractExternalClassSource(output, {
    className,
    resolveSourcesJar: async (coordinates) => {
      const r = await resolveSourcesJar(consumerRoot, coordinates);
      return r.ok ? r.sourcesJarPath : null;
    },
  });
}

describe.skipIf(!scenarioReady)('gradle/local-maven-publish scenario (real Gradle)', () => {
  let prevCache: string | undefined;
  let prevLocalRepo: string | undefined;
  let tmpCache: string;
  let localMavenRepo: string;
  let originalGreeterSrc: string;

  beforeEach(() => {
    tmpCache = fs.mkdtempSync(path.join(os.tmpdir(), 'jvmsrc-local-maven-'));
    localMavenRepo = path.join(tmpCache, 'local-repo');
    fs.mkdirSync(localMavenRepo, { recursive: true });

    prevCache = process.env.JVMSRC_CACHE_ROOT;
    process.env.JVMSRC_CACHE_ROOT = tmpCache;

    // Set the env var that both producer/build.gradle and consumer/build.gradle read.
    prevLocalRepo = process.env.JVMSRC_LOCAL_MAVEN_REPO;
    process.env.JVMSRC_LOCAL_MAVEN_REPO = localMavenRepo;

    // Snapshot the original Greeter.java so we can restore it after the test.
    originalGreeterSrc = fs.readFileSync(greeterSrc, 'utf8');
  });

  afterEach(() => {
    // Restore Greeter.java to its committed state.
    fs.writeFileSync(greeterSrc, originalGreeterSrc, 'utf8');

    if (prevCache === undefined) {
      delete process.env.JVMSRC_CACHE_ROOT;
    } else {
      process.env.JVMSRC_CACHE_ROOT = prevCache;
    }

    if (prevLocalRepo === undefined) {
      delete process.env.JVMSRC_LOCAL_MAVEN_REPO;
    } else {
      process.env.JVMSRC_LOCAL_MAVEN_REPO = prevLocalRepo;
    }

    try {
      fs.rmSync(tmpCache, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  });

  test('resolves Greeter.greet() from snapshot jar after initial publish', async () => {
    await runGradle(producerRoot, 'publish');

    const resolved = await resolveWithResolutionCache(consumerRoot, { forceRefresh: true });
    expect(resolved.ok).toBe(true);
    if (!resolved.ok) return;

    const got = await extractWithSources(resolved.output, 'com.example.lib.Greeter');
    expect(got.ok).toBe(true);
    if (!got.ok) return;

    expect(got.source).toContain('public class Greeter');
    expect(got.source).toContain('greet');
    expect(got.source).not.toContain('farewell');
  });

  test('automatically picks up new farewell() method after snapshot republication (no forceRefresh needed)', async () => {
    // Publish v1 — only greet() exists.
    await runGradle(producerRoot, 'publish');

    // Resolve consumer and confirm greet() is there, farewell() is absent.
    const v1 = await resolveWithResolutionCache(consumerRoot, { forceRefresh: true });
    expect(v1.ok).toBe(true);
    if (!v1.ok) return;

    const srcV1 = await extractWithSources(v1.output, 'com.example.lib.Greeter');
    expect(srcV1.ok).toBe(true);
    if (!srcV1.ok) return;
    expect(srcV1.source).toContain('greet');
    expect(srcV1.source).not.toContain('farewell');

    // Add farewell() to Greeter.java and republish — the JAR bytes change.
    const greeterWithFarewell = originalGreeterSrc.replace(
      /(\s*}\s*)$/,
      `
    /** Says goodbye. Added in v2. */
    public String farewell(String name) {
        return "Goodbye, " + name + "!";
    }
$1`,
    );
    fs.writeFileSync(greeterSrc, greeterWithFarewell, 'utf8');
    await runGradle(producerRoot, 'publish');

    // Resolve WITHOUT forceRefresh — the local-artifact digest detects the changed JAR,
    // causes a cache miss, Gradle re-runs, and the new snapshot is picked up automatically.
    const v2 = await resolveWithResolutionCache(consumerRoot, { forceRefresh: false });
    expect(v2.ok).toBe(true);
    if (!v2.ok) return;

    const srcV2 = await extractWithSources(v2.output, 'com.example.lib.Greeter');
    expect(srcV2.ok).toBe(true);
    if (!srcV2.ok) return;
    expect(srcV2.source).toContain('farewell');
  });

  test('cache is hit (no re-resolution) when snapshot content has not changed', async () => {
    await runGradle(producerRoot, 'publish');

    // First resolve — cold cache.
    const r1 = await resolveWithResolutionCache(consumerRoot, { forceRefresh: true });
    expect(r1.ok).toBe(true);
    if (!r1.ok) return;

    // Second resolve — no changes; should be a cache hit with the same resolvedAt timestamp.
    const r2 = await resolveWithResolutionCache(consumerRoot, { forceRefresh: false });
    expect(r2.ok).toBe(true);
    if (!r2.ok) return;

    expect(r2.output.resolvedAt).toBe(r1.output.resolvedAt);
  });
});
