import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, setDefaultTimeout, test } from 'bun:test';
import { extractExternalClassSource } from '../../../../src/extractor/extract-external-class-source.js';
import { resolveWithResolutionCache } from '../../../../src/resolve-with-cache.js';

setDefaultTimeout(120_000);

/**
 * Real-Gradle scenario: editing gradle.properties (not build.gradle) triggers automatic
 * cache invalidation and re-resolution when the version variable changes.
 *
 * The scenario:
 *   - `lib/` publishes `com.example:greeter-lib` at two stable versions via a temp local Maven repo:
 *       v1.0.0 — `Greeter` has only `greet()`
 *       v2.0.0 — `Greeter` has `greet()` + `greetLoud()`
 *   - `app/` declares the dependency as:
 *         implementation "com.example:greeter-lib:${greeterLibVersion}"
 *     where `greeterLibVersion` is read from `app/gradle.properties` (not from build.gradle).
 *
 * Tests verify:
 *   1. Tool resolves v1 and sees `greet()` but not `greetLoud()`.
 *   2. After editing ONLY `gradle.properties` to bump to v2.0.0 (build.gradle unchanged,
 *      no forceRefresh), the build-input digest changes → cache miss → Gradle re-runs →
 *      `greetLoud()` is now visible.
 *   3. A subsequent resolve with no changes returns the cached result (same `resolvedAt`).
 *
 * Requires wrapper JARs generated by scripts/ensure-scenario-wrappers.sh.
 * Silently skipped in CI when wrappers are absent.
 */

const scenarioRoot = path.resolve(import.meta.dir);
const libRoot = path.join(scenarioRoot, 'lib');
const appRoot = path.join(scenarioRoot, 'app');
const libWrapperJar = path.join(libRoot, 'gradle/wrapper/gradle-wrapper.jar');
const appWrapperJar = path.join(appRoot, 'gradle/wrapper/gradle-wrapper.jar');
const greeterSrc = path.join(libRoot, 'src/main/java/com/example/props/Greeter.java');
const appGradleProperties = path.join(appRoot, 'gradle.properties');

const scenarioReady = fs.existsSync(libWrapperJar) && fs.existsSync(appWrapperJar);

async function runGradle(projectDir: string, ...args: string[]): Promise<void> {
  const gradlew = path.join(projectDir, 'gradlew');
  const proc = Bun.spawn([gradlew, '--no-daemon', '--quiet', ...args], {
    cwd: projectDir,
    env: { ...process.env },
    stdout: 'inherit',
    stderr: 'inherit',
  });
  const code = await proc.exited;
  if (code !== 0) {
    throw new Error(`Gradle ${args.join(' ')} in ${path.basename(projectDir)} exited with code ${code}`);
  }
}

// Shared state populated by beforeAll — both versions published once for all tests.
let sharedTmpDir = '';
let sharedLocalRepo = '';
let originalGreeterSrc = '';
let originalGradleProperties = '';

if (scenarioReady) {
  beforeAll(async () => {
    sharedTmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'jvmsrc-gp-version-shared-'));
    sharedLocalRepo = path.join(sharedTmpDir, 'local-repo');
    fs.mkdirSync(sharedLocalRepo, { recursive: true });

    originalGreeterSrc = fs.readFileSync(greeterSrc, 'utf8');
    originalGradleProperties = fs.readFileSync(appGradleProperties, 'utf8');

    process.env.JVMSRC_LOCAL_MAVEN_REPO = sharedLocalRepo;

    // Publish v1.0.0 — Greeter has only greet().
    await runGradle(libRoot, 'publish', '-Pversion=1.0.0');

    // Add greetLoud() to Greeter.java, publish v2.0.0, then restore source.
    const v2Src = originalGreeterSrc.replace(
      /(\s*}\s*)$/,
      `
    /** Returns a loud greeting. Added in 2.0.0. */
    public String greetLoud(String name) {
        return greet(name).toUpperCase();
    }
$1`,
    );
    fs.writeFileSync(greeterSrc, v2Src, 'utf8');
    await runGradle(libRoot, 'publish', '-Pversion=2.0.0');
    fs.writeFileSync(greeterSrc, originalGreeterSrc, 'utf8');
  });

  afterAll(() => {
    fs.writeFileSync(greeterSrc, originalGreeterSrc, 'utf8');
    fs.writeFileSync(appGradleProperties, originalGradleProperties, 'utf8');
    delete process.env.JVMSRC_LOCAL_MAVEN_REPO;
    try {
      fs.rmSync(sharedTmpDir, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  });
}

describe.skipIf(!scenarioReady)('gradle/gradle-properties-version scenario (real Gradle)', () => {
  let prevCache: string | undefined;
  let tmpCache: string;

  beforeEach(() => {
    // Fresh isolated cache per test; restore gradle.properties to v1 baseline.
    tmpCache = fs.mkdtempSync(path.join(os.tmpdir(), 'jvmsrc-gp-version-'));
    prevCache = process.env.JVMSRC_CACHE_ROOT;
    process.env.JVMSRC_CACHE_ROOT = tmpCache;
    if (originalGradleProperties) {
      fs.writeFileSync(appGradleProperties, originalGradleProperties, 'utf8');
    }
  });

  afterEach(() => {
    if (originalGradleProperties) {
      fs.writeFileSync(appGradleProperties, originalGradleProperties, 'utf8');
    }
    if (prevCache === undefined) {
      delete process.env.JVMSRC_CACHE_ROOT;
    } else {
      process.env.JVMSRC_CACHE_ROOT = prevCache;
    }
    try {
      fs.rmSync(tmpCache, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  });

  test('resolves Greeter with only greet() when gradle.properties pins v1.0.0', async () => {
    const resolved = await resolveWithResolutionCache(appRoot, { forceRefresh: true });
    expect(resolved.ok).toBe(true);
    if (!resolved.ok) return;

    const got = await extractExternalClassSource(resolved.output, {
      className: 'com.example.props.Greeter',
    });
    expect(got.ok).toBe(true);
    if (!got.ok) return;

    expect(got.source).toContain('greet');
    expect(got.source).not.toContain('greetLoud');
  });

  test('automatically re-resolves after gradle.properties bumps version from 1.0.0 to 2.0.0 (no forceRefresh, build.gradle unchanged)', async () => {
    // Cold resolve with v1 — populates cache.
    const r1 = await resolveWithResolutionCache(appRoot, { forceRefresh: true });
    expect(r1.ok).toBe(true);
    if (!r1.ok) return;

    const src1 = await extractExternalClassSource(r1.output, {
      className: 'com.example.props.Greeter',
    });
    expect(src1.ok).toBe(true);
    if (!src1.ok) return;
    expect(src1.source).not.toContain('greetLoud');

    // Edit ONLY gradle.properties — build.gradle is untouched.
    fs.writeFileSync(appGradleProperties, 'greeterLibVersion=2.0.0\n', 'utf8');

    // Resolve without forceRefresh — gradle.properties changed → digest mismatch → cache miss.
    const r2 = await resolveWithResolutionCache(appRoot, { forceRefresh: false });
    expect(r2.ok).toBe(true);
    if (!r2.ok) return;

    const src2 = await extractExternalClassSource(r2.output, {
      className: 'com.example.props.Greeter',
    });
    expect(src2.ok).toBe(true);
    if (!src2.ok) return;
    expect(src2.source).toContain('greetLoud');

    const artifact = r2.output.modules
      .flatMap((m) => m.configurations)
      .flatMap((c) => c.artifacts)
      .find((a) => a.name === 'greeter-lib');
    expect(artifact?.version).toBe('2.0.0');
  });

  test('cache is hit on second resolve when gradle.properties has not changed', async () => {
    const r1 = await resolveWithResolutionCache(appRoot, { forceRefresh: true });
    expect(r1.ok).toBe(true);
    if (!r1.ok) return;

    const r2 = await resolveWithResolutionCache(appRoot, { forceRefresh: false });
    expect(r2.ok).toBe(true);
    if (!r2.ok) return;

    expect(r2.output.resolvedAt).toBe(r1.output.resolvedAt);
  });
});
