import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, setDefaultTimeout, test } from 'bun:test';
import { extractExternalClassSource } from '../../../../src/extractor/extract-external-class-source.js';
import { resolveWithResolutionCache } from '../../../../src/resolve-with-cache.js';

setDefaultTimeout(120_000);

/**
 * Real-Gradle scenario: multi-module inter-project source resolution.
 *
 * Requires:
 *   - `gradle` on PATH (first run, to generate the wrapper JAR via ensure-scenario-wrappers.sh)
 *   - `gradle/wrapper/gradle-wrapper.jar` present (generated by scripts/ensure-scenario-wrappers.sh)
 *
 * These tests are intentionally skipped when the wrapper JAR is absent (CI without Gradle).
 */
const scenarioRoot = path.resolve(import.meta.dir);
const wrapperJar = path.join(scenarioRoot, 'gradle/wrapper/gradle-wrapper.jar');

const scenarioReady = fs.existsSync(wrapperJar);

describe.skipIf(!scenarioReady)('gradle/multi-module scenario (real Gradle)', () => {
  let prevCache: string | undefined;
  let tmpCache: string;

  beforeEach(() => {
    tmpCache = fs.mkdtempSync(path.join(os.tmpdir(), 'jvmsrc-multi-module-'));
    prevCache = process.env.JVMSRC_CACHE_ROOT;
    process.env.JVMSRC_CACHE_ROOT = tmpCache;
  });

  afterEach(() => {
    if (prevCache === undefined) {
      delete process.env.JVMSRC_CACHE_ROOT;
    } else {
      process.env.JVMSRC_CACHE_ROOT = prevCache;
    }
    try {
      fs.rmSync(tmpCache, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  });

  test('resolves inter-project Library.java source from :app compileClasspath', async () => {
    const resolved = await resolveWithResolutionCache(scenarioRoot, { forceRefresh: true });
    expect(resolved.ok).toBe(true);
    if (!resolved.ok) return;

    const got = await extractExternalClassSource(resolved.output, {
      className: 'com.example.multimodule.Library',
      modulePath: ':app',
    });
    expect(got.ok).toBe(true);
    if (!got.ok) return;

    expect(got.source).toContain('public class Library');
    expect(got.source).toContain('greeting');
    expect(got.sourceAvailable).toBe(true);
    expect(got.provenance.kind).toBe('interproject');
  });

  test('resolution cache hit returns same output without re-invoking Gradle', async () => {
    // First call populates the cache.
    const first = await resolveWithResolutionCache(scenarioRoot, { forceRefresh: true });
    expect(first.ok).toBe(true);

    // Second call should hit the cache (no forceRefresh).
    const second = await resolveWithResolutionCache(scenarioRoot, { forceRefresh: false });
    expect(second.ok).toBe(true);
    if (!first.ok || !second.ok) return;

    expect(second.output.projectRoot).toBe(first.output.projectRoot);
    expect(second.output.modules.map((m) => m.name).sort()).toEqual(
      first.output.modules.map((m) => m.name).sort(),
    );
  });
});
