import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, setDefaultTimeout, test } from 'bun:test';
import { extractExternalClassSource } from '../../../../src/extractor/extract-external-class-source.js';
import { resolveWithResolutionCache } from '../../../../src/resolve-with-cache.js';

setDefaultTimeout(120_000);

/**
 * Real-Gradle scenario: build-file change triggers automatic cache invalidation and re-resolution.
 *
 * The scenario:
 *   - `lib/` publishes `com.example:calc-lib` at two stable versions via a temp local Maven repo:
 *       v1.0.0 — `Calculator` has only `add()`
 *       v2.0.0 — `Calculator` has `add()` + `multiply()`
 *   - `app/` starts with `implementation 'com.example:calc-lib:1.0.0'`
 *
 * Tests verify:
 *   1. Tool resolves v1 and sees `add()` but not `multiply()`.
 *   2. After editing `app/build.gradle` to use v2.0.0 (no forceRefresh), the build-input digest
 *      changes → cache miss → Gradle re-runs → `multiply()` is now visible.
 *   3. A subsequent resolve with no changes returns the cached result (same `resolvedAt`).
 *
 * beforeAll/afterAll (registered only when scenarioReady) publish both versions once.
 * Each test gets its own isolated JVMSRC_CACHE_ROOT via beforeEach/afterEach.
 *
 * Requires wrapper JARs generated by scripts/ensure-scenario-wrappers.sh.
 * Silently skipped in CI when wrappers are absent.
 */

const scenarioRoot = path.resolve(import.meta.dir);
const libRoot = path.join(scenarioRoot, 'lib');
const appRoot = path.join(scenarioRoot, 'app');
const libWrapperJar = path.join(libRoot, 'gradle/wrapper/gradle-wrapper.jar');
const appWrapperJar = path.join(appRoot, 'gradle/wrapper/gradle-wrapper.jar');
const calcSrc = path.join(libRoot, 'src/main/java/com/example/calc/Calculator.java');
const appBuildGradle = path.join(appRoot, 'build.gradle');

const scenarioReady = fs.existsSync(libWrapperJar) && fs.existsSync(appWrapperJar);

async function runGradle(projectDir: string, ...args: string[]): Promise<void> {
  const gradlew = path.join(projectDir, 'gradlew');
  const proc = Bun.spawn([gradlew, '--no-daemon', '--quiet', ...args], {
    cwd: projectDir,
    env: { ...process.env },
    stdout: 'inherit',
    stderr: 'inherit',
  });
  const code = await proc.exited;
  if (code !== 0) {
    throw new Error(`Gradle ${args.join(' ')} in ${path.basename(projectDir)} exited with code ${code}`);
  }
}

// Shared state populated by beforeAll — both versions published once for all tests.
let sharedTmpDir = '';
let sharedLocalRepo = '';
let originalCalcSrc = '';
let originalAppBuildGradle = '';

if (scenarioReady) {
  beforeAll(async () => {
    sharedTmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'jvmsrc-dep-change-shared-'));
    sharedLocalRepo = path.join(sharedTmpDir, 'local-repo');
    fs.mkdirSync(sharedLocalRepo, { recursive: true });

    originalCalcSrc = fs.readFileSync(calcSrc, 'utf8');
    originalAppBuildGradle = fs.readFileSync(appBuildGradle, 'utf8');

    process.env.JVMSRC_LOCAL_MAVEN_REPO = sharedLocalRepo;

    // Publish v1.0.0 — Calculator has only add().
    await runGradle(libRoot, 'publish', '-Pversion=1.0.0');

    // Add multiply() to Calculator.java, publish v2.0.0, then restore source.
    const v2Src = originalCalcSrc.replace(
      /(\s*}\s*)$/,
      `
    /** Multiplies two numbers. Added in 2.0.0. */
    public int multiply(int a, int b) {
        return a * b;
    }
$1`,
    );
    fs.writeFileSync(calcSrc, v2Src, 'utf8');
    await runGradle(libRoot, 'publish', '-Pversion=2.0.0');
    fs.writeFileSync(calcSrc, originalCalcSrc, 'utf8');
  });

  afterAll(() => {
    fs.writeFileSync(calcSrc, originalCalcSrc, 'utf8');
    fs.writeFileSync(appBuildGradle, originalAppBuildGradle, 'utf8');
    delete process.env.JVMSRC_LOCAL_MAVEN_REPO;
    try {
      fs.rmSync(sharedTmpDir, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  });
}

describe.skipIf(!scenarioReady)('gradle/dependency-change scenario (real Gradle)', () => {
  let prevCache: string | undefined;
  let tmpCache: string;

  beforeEach(() => {
    // Fresh isolated cache per test; restore app/build.gradle to v1 baseline.
    tmpCache = fs.mkdtempSync(path.join(os.tmpdir(), 'jvmsrc-dep-change-'));
    prevCache = process.env.JVMSRC_CACHE_ROOT;
    process.env.JVMSRC_CACHE_ROOT = tmpCache;
    if (originalAppBuildGradle) {
      fs.writeFileSync(appBuildGradle, originalAppBuildGradle, 'utf8');
    }
  });

  afterEach(() => {
    if (originalAppBuildGradle) {
      fs.writeFileSync(appBuildGradle, originalAppBuildGradle, 'utf8');
    }
    if (prevCache === undefined) {
      delete process.env.JVMSRC_CACHE_ROOT;
    } else {
      process.env.JVMSRC_CACHE_ROOT = prevCache;
    }
    try {
      fs.rmSync(tmpCache, { recursive: true, force: true });
    } catch {
      /* ignore */
    }
  });

  test('resolves Calculator with only add() when app depends on lib v1.0.0', async () => {
    const resolved = await resolveWithResolutionCache(appRoot, { forceRefresh: true });
    expect(resolved.ok).toBe(true);
    if (!resolved.ok) return;

    const got = await extractExternalClassSource(resolved.output, {
      className: 'com.example.calc.Calculator',
    });
    expect(got.ok).toBe(true);
    if (!got.ok) return;

    expect(got.source).toContain('add');
    expect(got.source).not.toContain('multiply');
  });

  test('automatically re-resolves after build.gradle changes version from 1.0.0 to 2.0.0 (no forceRefresh)', async () => {
    // Cold resolve with v1 — populates cache.
    const r1 = await resolveWithResolutionCache(appRoot, { forceRefresh: true });
    expect(r1.ok).toBe(true);
    if (!r1.ok) return;

    const src1 = await extractExternalClassSource(r1.output, {
      className: 'com.example.calc.Calculator',
    });
    expect(src1.ok).toBe(true);
    if (!src1.ok) return;
    expect(src1.source).not.toContain('multiply');

    // Edit build.gradle: bump the dependency version to 2.0.0.
    const updatedBuildGradle = originalAppBuildGradle.replace(
      "implementation 'com.example:calc-lib:1.0.0'",
      "implementation 'com.example:calc-lib:2.0.0'",
    );
    fs.writeFileSync(appBuildGradle, updatedBuildGradle, 'utf8');

    // Resolve without forceRefresh — build.gradle changed → digest mismatch → cache miss.
    const r2 = await resolveWithResolutionCache(appRoot, { forceRefresh: false });
    expect(r2.ok).toBe(true);
    if (!r2.ok) return;

    const src2 = await extractExternalClassSource(r2.output, {
      className: 'com.example.calc.Calculator',
    });
    expect(src2.ok).toBe(true);
    if (!src2.ok) return;
    expect(src2.source).toContain('multiply');

    const artifact = r2.output.modules
      .flatMap((m) => m.configurations)
      .flatMap((c) => c.artifacts)
      .find((a) => a.name === 'calc-lib');
    expect(artifact?.version).toBe('2.0.0');
  });

  test('cache is hit on second resolve when build.gradle has not changed', async () => {
    const r1 = await resolveWithResolutionCache(appRoot, { forceRefresh: true });
    expect(r1.ok).toBe(true);
    if (!r1.ok) return;

    const r2 = await resolveWithResolutionCache(appRoot, { forceRefresh: false });
    expect(r2.ok).toBe(true);
    if (!r2.ok) return;

    expect(r2.output.resolvedAt).toBe(r1.output.resolvedAt);
  });
});
